### ISSUE TITLE
Details on pylsl improvements?

### ISSUE THREAD

**Issue by DominiqueMakowski** [fcbg-hnp-meeg/bsl#95]
Just stumbled upon this repo, and this line caught my interest: "improved python-binding for the Lab Streaming Layer C++ library, bsl.lsl, replacing pylsl"

I am currently using pylsl to stream mostly some EEG and bodily signals data that I then record & save using the [LabRecorder](https://github.com/labstreaminglayer/App-LabRecorder) app.

And I was wondering if I should consider swapping pylsl in favour bsl? Any details on the existing/planned improvements or features?

Thanks!

**Comment by mscheltienne** [comment]
Hello, I would highly encourage you to swap. The module `bsl.lsl` is a re-implementation of `pylsl` with better documentation, testing, convenience methods and performance for numerical types. Pulling a chunk of data with `pylsl` is slow and has O(n) complexity scaling with the number of samples in the chunk, while with `bsl.lsl`, it's fast and has O(1) complexity (thanks `numpy`!). In numbers, with `float64` and a buffer of 2048 samples, a pull of 1024 samples from the C buffer to the python API takes:

- 7.87 ms ± 58 µs per loop with `pylsl`
- 4.35 µs ± 134 ns per loop with `bsl.lsl`

Beside the performance improvement, you'll also find some convenience methods to get/set the channel name/type/unit of a StreamInfo (not yet on main). Overall, the API has large similarities with `pylsl` since it's only a backward incompatible re-implementation. API documentation: https://fcbg-hnp-meeg.github.io/bsl/dev/api/lsl.html

-------

All that said, I would not encourage you to use anything else than `bsl.lsl`. The other modules are a bit old, inconvenient and error prone. I'm in the process of doing a major overall in https://github.com/fcbg-hnp-meeg/bsl/pull/93 and in a couple of subsequent PRs to fully integrate LSL with MNE-Python. `bsl.lsl` is part of the new API, but the other modules will be removed in the coming version `1.0`. I expect this overall to be complete and this library to be in a finish state around the end of September, at which point it might get renamed and moved to the `mne-tools` namespace.

**Comment by mscheltienne** [comment]
I will document the difference between `pylsl` and `bsl.lsl` on the website before the end of September.

**Comment by mscheltienne** [comment]
And for a bit more detail on the pull_chunk improvement, this is the bottleneck in `pylsl`: https://github.com/labstreaminglayer/pylsl/blob/16a4198087936386e866d7239bfde32d1fef6d6b/pylsl/pylsl.py#L866-L867

**Comment by DominiqueMakowski** [comment]
Sounds amazing, thanks for the hard cord ☺️ 

I was also considering doing a re-write of [muse-lsl](https://github.com/alexandrebarachant/muse-lsl) (to record Muse EEG) which seems unmaintained (?) and lacks some critical updates. It relies on pylsl currently. What do you think would be the best approach? Swapping pylsl for bsl in that, or directly implementing support for Muse streaming somewhere else like here? or in mne-realtime? (I'm new to the lsl ecosystem)

> All that said, I would not encourage you to use anything else than bsl.lsl

Do you mean avoiding using labrecorder? If so, is there a way to concurrently record various streams and save them in a BIDS-like format, using for instance MNE-bids?

**Comment by mscheltienne** [comment]
> Do you mean avoiding using labrecorder? If so, is there a way to concurrently record various streams and save them in a BIDS-like format, using for instance MNE-bids?

On the contrary, LabRecorder is great and I encourage people to use it.
I will probably add at a later stage in this package a `recorder` module with 2 options: `.xdf` via LabRecorder (but through a python API) and `.fif` (I think it should be fairly simple to pull chunks and write segment by segment into a FIFF file). 

-------------

I never worked with the muse systems, but in any case:
- The application which creates the LSL stream (i.e. which holds the StreamOutlet and pushes newly acquired data from the device onto the LSL outlet) should be in its own repository. Each device has its own API and its own "way" to communicate with the computer, with python. Non-exhaustive list of device LSL applications: https://github.com/sccn/labstreaminglayer/tree/master/Apps
- The main issue of writing an application in python which communicate with a device, retrieve new data, and pushes it on an LSL StreamOutlet; is the time-management (timestamps). If you do:

```
outlet = StreamOutlet(...)
device = DeviceInterface()  # object to communicate with the device
while True:
    if device.newData():
        data = device.getNewData()
        outlet.push_chunk(data)
```

and rely on the device to give you new data at a very **regular** and **consistent** rate, rely on the loop to retrieve this new data and to push it on the outlet at a very **regular** and **consistent** rate, you'll notice that it will fail spectacularly. For instance if you have a theoretical sampling rate of 200 Hz, you might end up with an effective sampling rate between 100 and 300 Hz, varying all the time.

The key point to fix this issue is to have the device tell you when was the information acquired, and what is the current time. With those 2 pieces of information, you can figure out the LSL timestamp corresponding to the newly acquired data and you can force the timestamp during the `outlet.push` operation. 

Example with the ViewPoint eye-tracker from arrington research: https://github.com/fcbg-hnp-meeg/lsl-viewpoint/blob/0442b138fd1ab39b7682e27d8bc93a61572451b6/lsl_viewpoint/callback.py#L293-L298

With details:
```
# Retrieve the current LSL time and the current time as advertised by the
# device. Both values correspond to "now", but with different time origin.
current_lsl_time = local_clock()
current_vpx_time = VPX.VPX_GetPrecisionDeltaTime(None, c_int(0))
```

Then:
```
# when was the received information measured, in device-timeframe
acquisition_time = DEVICE.data_time[eye].value
# what is the delay between the measure and now
delay = current_vpx_time - acquisition_time
# what is the corresponding timestamp in the LSL-timeframe
timestamp = current_lsl_time - delay
```

The main take away here is that all systems, all devices, do not offer the possibility to get the current time and to get the time at which new data has been acquired. And without those 2 pieces information, you will not be able to make a reliable LSL stream out of the information coming from your device.

------

Now that this time stamping issue is out, you can use either `pylsl` or `bsl.lsl` to create the `StreamOutlet`. Both will work. With the future versions of `bsl.lsl`, you'll be able to create the `StreamInfo` with the channel names, types, units, ... more easily than with `pylsl`. Example with the viewpoint system again, where I back ported the `set_channel_names`, `set_channel_types`, `set_channel_units` methods which are not yet available on main (available in #93): https://github.com/fcbg-hnp-meeg/lsl-viewpoint/blob/0442b138fd1ab39b7682e27d8bc93a61572451b6/lsl_viewpoint/callback.py#L219-L227

In one line, you can set all the channel names without having to bother figuring out how to work with the not that well documented `XMLElement` custom object used by `pylsl`, which under the hood, holds these information: https://github.com/labstreaminglayer/pylsl/blob/16a4198087936386e866d7239bfde32d1fef6d6b/pylsl/pylsl.py#L907-L1055

**Comment by mscheltienne** [comment]
For reference, that's how to add channel name/type/units with `pylsl`: https://github.com/labstreaminglayer/pylsl/blob/16a4198087936386e866d7239bfde32d1fef6d6b/pylsl/examples/SendDataAdvanced.py#L38-L52

And that's with #93:

```
sinfo = StreamInfo(...)
sinfo.set_channel_names(["name1", "name2", ...])
sinfo.set_channel_types("eeg")  # all eeg channels
sinfo.set_channel_units("uv")  # all in microvolts
```

**Comment by DominiqueMakowski** [comment]
sweet, thanks a lot. I'll let you know how it goes once I start working on that :) cheers!
